# rbenv
eval "$(rbenv init -)"

[ -d "/Users/jmeyer1/Code/8b/bin" ] && export PATH="/Users/jmeyer1/Code/8b/bin:$PATH"
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh
RUBIES+=(~/.rbenv/versions/*)
