ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="$HOME/dotfiles/custom"
ZSH_THEME="jeremy"

DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="false"

setopt auto_cd
setopt auto_pushd
setopt prompt_subst
setopt histignoredups
autoload -Uz compinit && compinit

source $ZSH/oh-my-zsh.sh

# fasd config
eval "$(fasd --init auto)"

# fix rake parameters
alias rake='noglob rake'

# tired of writing this
function include () {
  [[ -f "$1" ]] && . "$1"
}

# load personal settings
include ~/.localrc

# load settings for specific hostnames
include ~/dotfiles/hosts/$(ls ~/dotfiles/hosts | grep $(hostname -s))

# load rest of files
for file in ~/dotfiles/bash/*; do
  . "$file"
done
